spring.application.name=fitstore-core
spring.datasource.url=jdbc:postgresql://localhost:5433/fitstore?options=-c%20TimeZone=Asia/Kolkata
spring.datasource.username=fitstore
spring.datasource.password=fitstore
spring.jpa.hibernate.ddl-auto=none
spring.data.redis.host=localhost
spring.data.redis.port=6379